---
- hosts: all
  become: true
  tasks:
  - name: install nano text editor and net-tools  on Ubuntu
    apt:
      name: 
        - nano
        - net-tools
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: install apache2 and php  packages for Ubuntu
    apt:
      name: 
        - apache2 
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install nano text editor and net-tools on AlmaLinux
    dnf:
      name: 
        - nano
        - net-tools
    when: ansible_distribution == "AlmaLinux"

  - name: install apache2 and php packages on AlmaLinux
    dnf:
      name: 
        - httpd 
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"
