- name: installing nano and net-tools and apache2 and php and updating cache on Ubuntu
  tags: ubuntu,apache,nano,php,net-tools
  package:
      name:
        - "{{ nano_package }}"
        - "{{ net_tools_package }}"
        - "{{ apache_package_name }}"
        - "{{ php_package_name }}"
      state: latest

- name: start httpd (AlmaLinux)
  tags: apache,almalinux,httpd
  service:
      name: "{{ apache_service }}"
      state: started
      enabled: yes

- name: change email address for admin
  tags: apache,httpd,AlmaLinux
  lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regex: '^ServerAdmin'
      line: ServerAdmin somebody@moudir.com
  when: ansible_distribution == "AlmaLinux"
  register: apache
#register is a variable where we saved the play
- name: restart httpd (AlmaLinux)
  tags: apache,AlmaLinux,httpd
  service:
      name: "{{ apache_service}}"
      state: restarted
  when: apache.changed

- name: copy default html file for site
  tags: apache,php,httpd
  copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
