  - name: install unzip
    package:
     name: unzip
     state: latest
  - name: install terraform
    unarchive:
     src: https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
     dest: /usr/local/bin
     remote_src: yes
     mode: 0755
     owner: root
     group: root
